### PR TITLE
Add support for pagination, sort and search in offline mode

### LINKED ISSUE #78: Support pagination in offline mode
Offline mode should also support pagination

### LINKED ISSUE #79: Support sorting in offline mode
Offline mode should also support sorting.

### PR DESCRIPTION
**Pull request by jeremyvergnas**
feat(offlineMode): add support for pagination and sort
fix(offlineMode): add support for search

Fixes https://github.com/SpoonX/aurelia-datatable/issues/78
Fixes https://github.com/SpoonX/aurelia-datatable/issues/79

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@jeremyvergnas Is this still relevant?

**Comment by jeremyvergnas** [comment]
@RWOverdijk yes it is. Some extra features in offline mode

**Comment by RWOverdijk** [comment]
Okay, cool... Do you think you can resolve the conflicts then?

**Comment by RWOverdijk** [comment]
@jeremyvergnas Stiiiiiill think you need this? :p

**Comment by jeremyvergnas** [comment]
Well nobody uses data-table offline. So I guess you can close this one.

**Comment by RWOverdijk** [comment]
I know some people do, but I guess we can re-open this if they need it :)

**Pull request closed without merging**
