### PR TITLE
reset page on search

### LINKED ISSUE #50: Go to page 1 when searching
When we start a search with the `searchable` element, we should go back to page 1

### PR DESCRIPTION
**Pull request by natrim**
resolves #50

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Hey @natrim !

Thanks for contributing, it's appreciated. Could I request two changes from you?

1. Please change the commit message following our [contributing guidelines](https://github.com/SpoonX/about/blob/master/CONTRIBUTING.md#commit)
2. Please remove the build. We run those on-release, which is an automated process.

Thanks again!

**Comment by natrim** [comment]
@RWOverdijk changed and repushed

**Comment by natrim** [comment]
just one question: maybe i should use "PLATFORM.global.setTimeout" instead of only setTimeout ?

**Comment by RWOverdijk** [comment]
Hey! I'll review now :)You didn't remove the build (dist) though.

**Comment by natrim** [comment]
i did, the github is for some reason displaying last commit in the repo in this pull though

**Comment by natrim** [comment]
il repush it, it seems it somehow merged with the previous commit in the origin branch
and  i'l change the timeout to PLATFORM

**Comment by RWOverdijk** [comment]
@jeremyvergnas would you mind reviewing this?

**Comment by RWOverdijk** [comment]
Published in 0.8.2

**Pull request merged**
