### PR TITLE
Standardize build

### PR DESCRIPTION
**Pull request by doktordirk**
Updated dependencies
Updated build to aurelia default
Added adjustments for resources and standardized across repos
Updated typings entry where needed

new build+bump

### CODE REVIEW

**Comment by doktordirk** [comment]
@VMBindraban @RWOverdijk 
i'd like to merge and publish on npm, so i can upload my aurelia-todo-client bundeling fixes

**Comment by RWOverdijk** [comment]
@jeremyvergnas Please review

**Comment by RWOverdijk** [comment]
@doktordirk Never mind that, go ahead.

**Comment by doktordirk** [comment]
@RWOverdijk i tested the build on aurelia-todo-client without hitch (basically)

**Pull request merged**
